on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master

name: makefile build

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
  
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest}
          - {os: windows-latest}
          - {os: ubuntu-latest}
          
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    
    - name: check makefile build
      run: make
